project_name: gochange

build:
  goos:
    - windows
    - linux
    - darwin

archive:
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS

release:
  prerelease: true

